# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1166, 902)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(160, 70, 981, 761))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.groupBox = QtWidgets.QGroupBox(self.page_1)
        self.groupBox.setGeometry(QtCore.QRect(160, 150, 611, 281))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(10, 60, 54, 21))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_1.setGeometry(QtCore.QRect(50, 60, 113, 20))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(180, 60, 54, 16))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(230, 60, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(320, 60, 54, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 60, 41, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.Btn_New = QtWidgets.QPushButton(self.groupBox)
        self.Btn_New.setGeometry(QtCore.QRect(70, 170, 131, 31))
        self.Btn_New.setObjectName("Btn_New")
        self.Btn_Search = QtWidgets.QPushButton(self.groupBox)
        self.Btn_Search.setGeometry(QtCore.QRect(280, 170, 131, 31))
        self.Btn_Search.setObjectName("Btn_Search")
        self.label_page1 = QtWidgets.QLabel(self.page_1)
        self.label_page1.setGeometry(QtCore.QRect(10, 0, 54, 12))
        self.label_page1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page1.setObjectName("label_page1")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.groupBox_BackGround = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_BackGround.setGeometry(QtCore.QRect(60, 20, 711, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_BackGround.sizePolicy().hasHeightForWidth())
        self.groupBox_BackGround.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(14)
        self.groupBox_BackGround.setFont(font)
        self.groupBox_BackGround.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_BackGround.setObjectName("groupBox_BackGround")
        self.groupBox_Home = QtWidgets.QGroupBox(self.groupBox_BackGround)
        self.groupBox_Home.setGeometry(QtCore.QRect(20, 50, 231, 58))
        self.groupBox_Home.setObjectName("groupBox_Home")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_Home)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 27, 57, 21))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_Home)
        self.radioButton_4.setGeometry(QtCore.QRect(109, 27, 57, 21))
        self.radioButton_4.setObjectName("radioButton_4")
        self.groupBox_culture = QtWidgets.QGroupBox(self.groupBox_BackGround)
        self.groupBox_culture.setGeometry(QtCore.QRect(360, 130, 251, 81))
        self.groupBox_culture.setObjectName("groupBox_culture")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_culture)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_culture)
        self.radioButton_16.setObjectName("radioButton_16")
        self.gridLayout_3.addWidget(self.radioButton_16, 1, 1, 1, 1)
        self.radioButton_19 = QtWidgets.QRadioButton(self.groupBox_culture)
        self.radioButton_19.setObjectName("radioButton_19")
        self.gridLayout_3.addWidget(self.radioButton_19, 0, 1, 1, 1)
        self.radioButton_21 = QtWidgets.QRadioButton(self.groupBox_culture)
        self.radioButton_21.setObjectName("radioButton_21")
        self.gridLayout_3.addWidget(self.radioButton_21, 1, 0, 1, 1)
        self.radioButton_23 = QtWidgets.QRadioButton(self.groupBox_culture)
        self.radioButton_23.setObjectName("radioButton_23")
        self.gridLayout_3.addWidget(self.radioButton_23, 0, 0, 1, 1)
        self.groupBox_marriage = QtWidgets.QGroupBox(self.groupBox_BackGround)
        self.groupBox_marriage.setGeometry(QtCore.QRect(20, 130, 231, 85))
        self.groupBox_marriage.setObjectName("groupBox_marriage")
        self.radioButton_39 = QtWidgets.QRadioButton(self.groupBox_marriage)
        self.radioButton_39.setGeometry(QtCore.QRect(10, 27, 91, 21))
        self.radioButton_39.setObjectName("radioButton_39")
        self.radioButton_40 = QtWidgets.QRadioButton(self.groupBox_marriage)
        self.radioButton_40.setGeometry(QtCore.QRect(10, 54, 57, 21))
        self.radioButton_40.setObjectName("radioButton_40")
        self.radioButton_41 = QtWidgets.QRadioButton(self.groupBox_marriage)
        self.radioButton_41.setGeometry(QtCore.QRect(110, 27, 57, 21))
        self.radioButton_41.setObjectName("radioButton_41")
        self.groupBox_living = QtWidgets.QGroupBox(self.groupBox_BackGround)
        self.groupBox_living.setGeometry(QtCore.QRect(360, 50, 251, 61))
        self.groupBox_living.setObjectName("groupBox_living")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_living)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_45 = QtWidgets.QRadioButton(self.groupBox_living)
        self.radioButton_45.setObjectName("radioButton_45")
        self.gridLayout_5.addWidget(self.radioButton_45, 0, 0, 1, 1)
        self.radioButton_46 = QtWidgets.QRadioButton(self.groupBox_living)
        self.radioButton_46.setObjectName("radioButton_46")
        self.gridLayout_5.addWidget(self.radioButton_46, 0, 1, 1, 1)
        self.groupBox_smoking = QtWidgets.QGroupBox(self.groupBox_BackGround)
        self.groupBox_smoking.setGeometry(QtCore.QRect(20, 240, 231, 58))
        self.groupBox_smoking.setObjectName("groupBox_smoking")
        self.radioButton_47 = QtWidgets.QRadioButton(self.groupBox_smoking)
        self.radioButton_47.setGeometry(QtCore.QRect(10, 27, 40, 21))
        self.radioButton_47.setObjectName("radioButton_47")
        self.radioButton_66 = QtWidgets.QRadioButton(self.groupBox_smoking)
        self.radioButton_66.setGeometry(QtCore.QRect(110, 27, 40, 21))
        self.radioButton_66.setObjectName("radioButton_66")
        self.groupBox_drinking = QtWidgets.QGroupBox(self.groupBox_BackGround)
        self.groupBox_drinking.setGeometry(QtCore.QRect(360, 240, 251, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_drinking.sizePolicy().hasHeightForWidth())
        self.groupBox_drinking.setSizePolicy(sizePolicy)
        self.groupBox_drinking.setObjectName("groupBox_drinking")
        self.radioButton_67 = QtWidgets.QRadioButton(self.groupBox_drinking)
        self.radioButton_67.setGeometry(QtCore.QRect(10, 27, 40, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_67.sizePolicy().hasHeightForWidth())
        self.radioButton_67.setSizePolicy(sizePolicy)
        self.radioButton_67.setObjectName("radioButton_67")
        self.radioButton_68 = QtWidgets.QRadioButton(self.groupBox_drinking)
        self.radioButton_68.setGeometry(QtCore.QRect(130, 27, 40, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_68.sizePolicy().hasHeightForWidth())
        self.radioButton_68.setSizePolicy(sizePolicy)
        self.radioButton_68.setObjectName("radioButton_68")
        self.groupBox_family = QtWidgets.QGroupBox(self.groupBox_BackGround)
        self.groupBox_family.setGeometry(QtCore.QRect(20, 330, 231, 58))
        self.groupBox_family.setObjectName("groupBox_family")
        self.radioButton_69 = QtWidgets.QRadioButton(self.groupBox_family)
        self.radioButton_69.setGeometry(QtCore.QRect(10, 27, 40, 21))
        self.radioButton_69.setObjectName("radioButton_69")
        self.radioButton_70 = QtWidgets.QRadioButton(self.groupBox_family)
        self.radioButton_70.setGeometry(QtCore.QRect(110, 20, 40, 21))
        self.radioButton_70.setObjectName("radioButton_70")
        self.groupBox_noise = QtWidgets.QGroupBox(self.groupBox_BackGround)
        self.groupBox_noise.setGeometry(QtCore.QRect(360, 330, 251, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_noise.sizePolicy().hasHeightForWidth())
        self.groupBox_noise.setSizePolicy(sizePolicy)
        self.groupBox_noise.setObjectName("groupBox_noise")
        self.radioButton_71 = QtWidgets.QRadioButton(self.groupBox_noise)
        self.radioButton_71.setGeometry(QtCore.QRect(10, 27, 40, 21))
        self.radioButton_71.setObjectName("radioButton_71")
        self.radioButton_72 = QtWidgets.QRadioButton(self.groupBox_noise)
        self.radioButton_72.setGeometry(QtCore.QRect(130, 27, 40, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_72.sizePolicy().hasHeightForWidth())
        self.radioButton_72.setSizePolicy(sizePolicy)
        self.radioButton_72.setObjectName("radioButton_72")
        self.groupBox_drugs = QtWidgets.QGroupBox(self.groupBox_BackGround)
        self.groupBox_drugs.setGeometry(QtCore.QRect(20, 420, 581, 58))
        self.groupBox_drugs.setObjectName("groupBox_drugs")
        self.radioButton_73 = QtWidgets.QRadioButton(self.groupBox_drugs)
        self.radioButton_73.setGeometry(QtCore.QRect(10, 27, 40, 21))
        self.radioButton_73.setObjectName("radioButton_73")
        self.radioButton_74 = QtWidgets.QRadioButton(self.groupBox_drugs)
        self.radioButton_74.setGeometry(QtCore.QRect(110, 27, 40, 21))
        self.radioButton_74.setObjectName("radioButton_74")
        self.groupBox_chronic = QtWidgets.QGroupBox(self.groupBox_BackGround)
        self.groupBox_chronic.setGeometry(QtCore.QRect(20, 510, 591, 61))
        self.groupBox_chronic.setObjectName("groupBox_chronic")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_chronic)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_chronic)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_2.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_chronic)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_2.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_chronic)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_2.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_chronic)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_2.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_chronic)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_2.addWidget(self.checkBox_10)
        self.label_page2 = QtWidgets.QLabel(self.page_2)
        self.label_page2.setGeometry(QtCore.QRect(10, 0, 54, 12))
        self.label_page2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page2.setObjectName("label_page2")
        self.Btn_Save2 = QtWidgets.QPushButton(self.page_2)
        self.Btn_Save2.setGeometry(QtCore.QRect(800, 680, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Btn_Save2.setFont(font)
        self.Btn_Save2.setObjectName("Btn_Save2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.groupBox_HHIE = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_HHIE.setGeometry(QtCore.QRect(50, 0, 831, 751))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_HHIE.sizePolicy().hasHeightForWidth())
        self.groupBox_HHIE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox_HHIE.setFont(font)
        self.groupBox_HHIE.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_HHIE.setObjectName("groupBox_HHIE")
        self.groupBox3_1 = QtWidgets.QGroupBox(self.groupBox_HHIE)
        self.groupBox3_1.setGeometry(QtCore.QRect(50, 60, 601, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3_1.sizePolicy().hasHeightForWidth())
        self.groupBox3_1.setSizePolicy(sizePolicy)
        self.groupBox3_1.setObjectName("groupBox3_1")
        self.radioButton_75 = QtWidgets.QRadioButton(self.groupBox3_1)
        self.radioButton_75.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_75.setObjectName("radioButton_75")
        self.radioButton_76 = QtWidgets.QRadioButton(self.groupBox3_1)
        self.radioButton_76.setGeometry(QtCore.QRect(130, 30, 115, 16))
        self.radioButton_76.setObjectName("radioButton_76")
        self.radioButton_77 = QtWidgets.QRadioButton(self.groupBox3_1)
        self.radioButton_77.setGeometry(QtCore.QRect(270, 30, 89, 16))
        self.radioButton_77.setObjectName("radioButton_77")
        self.groupBox3_2 = QtWidgets.QGroupBox(self.groupBox_HHIE)
        self.groupBox3_2.setGeometry(QtCore.QRect(50, 120, 601, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3_2.sizePolicy().hasHeightForWidth())
        self.groupBox3_2.setSizePolicy(sizePolicy)
        self.groupBox3_2.setObjectName("groupBox3_2")
        self.radioButton_78 = QtWidgets.QRadioButton(self.groupBox3_2)
        self.radioButton_78.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_78.setObjectName("radioButton_78")
        self.radioButton_79 = QtWidgets.QRadioButton(self.groupBox3_2)
        self.radioButton_79.setGeometry(QtCore.QRect(130, 30, 115, 16))
        self.radioButton_79.setObjectName("radioButton_79")
        self.radioButton_80 = QtWidgets.QRadioButton(self.groupBox3_2)
        self.radioButton_80.setGeometry(QtCore.QRect(270, 30, 89, 16))
        self.radioButton_80.setObjectName("radioButton_80")
        self.groupBox3_8 = QtWidgets.QGroupBox(self.groupBox_HHIE)
        self.groupBox3_8.setGeometry(QtCore.QRect(50, 540, 601, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3_8.sizePolicy().hasHeightForWidth())
        self.groupBox3_8.setSizePolicy(sizePolicy)
        self.groupBox3_8.setObjectName("groupBox3_8")
        self.radioButton_81 = QtWidgets.QRadioButton(self.groupBox3_8)
        self.radioButton_81.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_81.setObjectName("radioButton_81")
        self.radioButton_82 = QtWidgets.QRadioButton(self.groupBox3_8)
        self.radioButton_82.setGeometry(QtCore.QRect(130, 30, 115, 16))
        self.radioButton_82.setObjectName("radioButton_82")
        self.radioButton_83 = QtWidgets.QRadioButton(self.groupBox3_8)
        self.radioButton_83.setGeometry(QtCore.QRect(270, 30, 89, 16))
        self.radioButton_83.setObjectName("radioButton_83")
        self.groupBox3_3 = QtWidgets.QGroupBox(self.groupBox_HHIE)
        self.groupBox3_3.setGeometry(QtCore.QRect(50, 180, 601, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3_3.sizePolicy().hasHeightForWidth())
        self.groupBox3_3.setSizePolicy(sizePolicy)
        self.groupBox3_3.setObjectName("groupBox3_3")
        self.radioButton_84 = QtWidgets.QRadioButton(self.groupBox3_3)
        self.radioButton_84.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_84.setObjectName("radioButton_84")
        self.radioButton_85 = QtWidgets.QRadioButton(self.groupBox3_3)
        self.radioButton_85.setGeometry(QtCore.QRect(130, 30, 115, 16))
        self.radioButton_85.setObjectName("radioButton_85")
        self.radioButton_86 = QtWidgets.QRadioButton(self.groupBox3_3)
        self.radioButton_86.setGeometry(QtCore.QRect(270, 30, 89, 16))
        self.radioButton_86.setObjectName("radioButton_86")
        self.label_3 = QtWidgets.QLabel(self.groupBox_HHIE)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 441, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.groupBox3_9 = QtWidgets.QGroupBox(self.groupBox_HHIE)
        self.groupBox3_9.setGeometry(QtCore.QRect(50, 610, 601, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3_9.sizePolicy().hasHeightForWidth())
        self.groupBox3_9.setSizePolicy(sizePolicy)
        self.groupBox3_9.setObjectName("groupBox3_9")
        self.radioButton_87 = QtWidgets.QRadioButton(self.groupBox3_9)
        self.radioButton_87.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_87.setObjectName("radioButton_87")
        self.radioButton_88 = QtWidgets.QRadioButton(self.groupBox3_9)
        self.radioButton_88.setGeometry(QtCore.QRect(130, 30, 115, 16))
        self.radioButton_88.setObjectName("radioButton_88")
        self.radioButton_89 = QtWidgets.QRadioButton(self.groupBox3_9)
        self.radioButton_89.setGeometry(QtCore.QRect(270, 30, 89, 16))
        self.radioButton_89.setObjectName("radioButton_89")
        self.groupBox3_7 = QtWidgets.QGroupBox(self.groupBox_HHIE)
        self.groupBox3_7.setGeometry(QtCore.QRect(50, 470, 601, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3_7.sizePolicy().hasHeightForWidth())
        self.groupBox3_7.setSizePolicy(sizePolicy)
        self.groupBox3_7.setObjectName("groupBox3_7")
        self.radioButton_90 = QtWidgets.QRadioButton(self.groupBox3_7)
        self.radioButton_90.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_90.setObjectName("radioButton_90")
        self.radioButton_91 = QtWidgets.QRadioButton(self.groupBox3_7)
        self.radioButton_91.setGeometry(QtCore.QRect(130, 30, 115, 16))
        self.radioButton_91.setObjectName("radioButton_91")
        self.radioButton_92 = QtWidgets.QRadioButton(self.groupBox3_7)
        self.radioButton_92.setGeometry(QtCore.QRect(270, 30, 89, 16))
        self.radioButton_92.setObjectName("radioButton_92")
        self.groupBox3_10 = QtWidgets.QGroupBox(self.groupBox_HHIE)
        self.groupBox3_10.setGeometry(QtCore.QRect(50, 680, 601, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3_10.sizePolicy().hasHeightForWidth())
        self.groupBox3_10.setSizePolicy(sizePolicy)
        self.groupBox3_10.setObjectName("groupBox3_10")
        self.radioButton_93 = QtWidgets.QRadioButton(self.groupBox3_10)
        self.radioButton_93.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_93.setObjectName("radioButton_93")
        self.radioButton_94 = QtWidgets.QRadioButton(self.groupBox3_10)
        self.radioButton_94.setGeometry(QtCore.QRect(130, 30, 115, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_94.sizePolicy().hasHeightForWidth())
        self.radioButton_94.setSizePolicy(sizePolicy)
        self.radioButton_94.setObjectName("radioButton_94")
        self.radioButton_95 = QtWidgets.QRadioButton(self.groupBox3_10)
        self.radioButton_95.setGeometry(QtCore.QRect(270, 30, 89, 16))
        self.radioButton_95.setObjectName("radioButton_95")
        self.groupBox3_6 = QtWidgets.QGroupBox(self.groupBox_HHIE)
        self.groupBox3_6.setGeometry(QtCore.QRect(50, 400, 601, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3_6.sizePolicy().hasHeightForWidth())
        self.groupBox3_6.setSizePolicy(sizePolicy)
        self.groupBox3_6.setObjectName("groupBox3_6")
        self.radioButton_96 = QtWidgets.QRadioButton(self.groupBox3_6)
        self.radioButton_96.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_96.setObjectName("radioButton_96")
        self.radioButton_97 = QtWidgets.QRadioButton(self.groupBox3_6)
        self.radioButton_97.setGeometry(QtCore.QRect(130, 30, 115, 16))
        self.radioButton_97.setObjectName("radioButton_97")
        self.radioButton_98 = QtWidgets.QRadioButton(self.groupBox3_6)
        self.radioButton_98.setGeometry(QtCore.QRect(270, 30, 89, 16))
        self.radioButton_98.setObjectName("radioButton_98")
        self.groupBox3_5 = QtWidgets.QGroupBox(self.groupBox_HHIE)
        self.groupBox3_5.setGeometry(QtCore.QRect(50, 330, 601, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3_5.sizePolicy().hasHeightForWidth())
        self.groupBox3_5.setSizePolicy(sizePolicy)
        self.groupBox3_5.setObjectName("groupBox3_5")
        self.radioButton_99 = QtWidgets.QRadioButton(self.groupBox3_5)
        self.radioButton_99.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_99.setObjectName("radioButton_99")
        self.radioButton_100 = QtWidgets.QRadioButton(self.groupBox3_5)
        self.radioButton_100.setGeometry(QtCore.QRect(130, 30, 115, 16))
        self.radioButton_100.setObjectName("radioButton_100")
        self.radioButton_101 = QtWidgets.QRadioButton(self.groupBox3_5)
        self.radioButton_101.setGeometry(QtCore.QRect(270, 30, 89, 16))
        self.radioButton_101.setObjectName("radioButton_101")
        self.groupBox3_4 = QtWidgets.QGroupBox(self.groupBox_HHIE)
        self.groupBox3_4.setGeometry(QtCore.QRect(50, 250, 601, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3_4.sizePolicy().hasHeightForWidth())
        self.groupBox3_4.setSizePolicy(sizePolicy)
        self.groupBox3_4.setObjectName("groupBox3_4")
        self.radioButton_102 = QtWidgets.QRadioButton(self.groupBox3_4)
        self.radioButton_102.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_102.setObjectName("radioButton_102")
        self.radioButton_103 = QtWidgets.QRadioButton(self.groupBox3_4)
        self.radioButton_103.setGeometry(QtCore.QRect(130, 30, 115, 16))
        self.radioButton_103.setObjectName("radioButton_103")
        self.radioButton_104 = QtWidgets.QRadioButton(self.groupBox3_4)
        self.radioButton_104.setGeometry(QtCore.QRect(270, 30, 89, 16))
        self.radioButton_104.setObjectName("radioButton_104")
        self.Btn_Save3 = QtWidgets.QPushButton(self.groupBox_HHIE)
        self.Btn_Save3.setGeometry(QtCore.QRect(730, 710, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Btn_Save3.setFont(font)
        self.Btn_Save3.setObjectName("Btn_Save3")
        self.label_page3 = QtWidgets.QLabel(self.page_3)
        self.label_page3.setGeometry(QtCore.QRect(10, 0, 54, 12))
        self.label_page3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page3.setObjectName("label_page3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.groupBox4_1 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox4_1.setGeometry(QtCore.QRect(40, 40, 831, 131))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(14)
        self.groupBox4_1.setFont(font)
        self.groupBox4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox4_1.setObjectName("groupBox4_1")
        self.tableWidget4_1 = QtWidgets.QTableWidget(self.groupBox4_1)
        self.tableWidget4_1.setGeometry(QtCore.QRect(190, 30, 431, 101))
        self.tableWidget4_1.setObjectName("tableWidget4_1")
        self.tableWidget4_1.setColumnCount(4)
        self.tableWidget4_1.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_1.setHorizontalHeaderItem(3, item)
        self.groupBox4_3 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox4_3.setGeometry(QtCore.QRect(40, 500, 871, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox4_3.setFont(font)
        self.groupBox4_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox4_3.setObjectName("groupBox4_3")
        self.tableWidget4_3 = QtWidgets.QTableWidget(self.groupBox4_3)
        self.tableWidget4_3.setGeometry(QtCore.QRect(0, 30, 861, 101))
        self.tableWidget4_3.setLineWidth(1)
        self.tableWidget4_3.setMidLineWidth(0)
        self.tableWidget4_3.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget4_3.setShowGrid(True)
        self.tableWidget4_3.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget4_3.setWordWrap(True)
        self.tableWidget4_3.setCornerButtonEnabled(True)
        self.tableWidget4_3.setColumnCount(8)
        self.tableWidget4_3.setObjectName("tableWidget4_3")
        self.tableWidget4_3.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_3.setHorizontalHeaderItem(7, item)
        self.groupBox4_2 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox4_2.setGeometry(QtCore.QRect(40, 260, 831, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox4_2.setFont(font)
        self.groupBox4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox4_2.setObjectName("groupBox4_2")
        self.tableWidget4_2 = QtWidgets.QTableWidget(self.groupBox4_2)
        self.tableWidget4_2.setGeometry(QtCore.QRect(90, 30, 681, 101))
        self.tableWidget4_2.setObjectName("tableWidget4_2")
        self.tableWidget4_2.setColumnCount(6)
        self.tableWidget4_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4_2.setHorizontalHeaderItem(5, item)
        self.label_page4 = QtWidgets.QLabel(self.page_4)
        self.label_page4.setGeometry(QtCore.QRect(10, 0, 54, 12))
        self.label_page4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page4.setObjectName("label_page4")
        self.Btn_Save4 = QtWidgets.QPushButton(self.page_4)
        self.Btn_Save4.setGeometry(QtCore.QRect(810, 690, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Btn_Save4.setFont(font)
        self.Btn_Save4.setObjectName("Btn_Save4")
        self.stackedWidget.addWidget(self.page_4)
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setGeometry(QtCore.QRect(150, 0, 931, 60))
        self.frame_1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_1.setLineWidth(5)
        self.frame_1.setObjectName("frame_1")
        self.softname = QtWidgets.QLabel(self.frame_1)
        self.softname.setGeometry(QtCore.QRect(220, 10, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.softname.setFont(font)
        self.softname.setObjectName("softname")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 60, 150, 771))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(5)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 111, 681))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Btn1_BaseInfo = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn1_BaseInfo.sizePolicy().hasHeightForWidth())
        self.Btn1_BaseInfo.setSizePolicy(sizePolicy)
        self.Btn1_BaseInfo.setCheckable(False)
        self.Btn1_BaseInfo.setChecked(False)
        self.Btn1_BaseInfo.setAutoExclusive(False)
        self.Btn1_BaseInfo.setAutoDefault(True)
        self.Btn1_BaseInfo.setObjectName("Btn1_BaseInfo")
        self.verticalLayout.addWidget(self.Btn1_BaseInfo)
        self.Btn2_Backgroud = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn2_Backgroud.sizePolicy().hasHeightForWidth())
        self.Btn2_Backgroud.setSizePolicy(sizePolicy)
        self.Btn2_Backgroud.setCheckable(False)
        self.Btn2_Backgroud.setChecked(False)
        self.Btn2_Backgroud.setAutoExclusive(False)
        self.Btn2_Backgroud.setObjectName("Btn2_Backgroud")
        self.verticalLayout.addWidget(self.Btn2_Backgroud)
        self.Btn3_HHIES = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn3_HHIES.sizePolicy().hasHeightForWidth())
        self.Btn3_HHIES.setSizePolicy(sizePolicy)
        self.Btn3_HHIES.setCheckable(False)
        self.Btn3_HHIES.setChecked(False)
        self.Btn3_HHIES.setAutoExclusive(False)
        self.Btn3_HHIES.setObjectName("Btn3_HHIES")
        self.verticalLayout.addWidget(self.Btn3_HHIES)
        self.Btn4_Estimate = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn4_Estimate.sizePolicy().hasHeightForWidth())
        self.Btn4_Estimate.setSizePolicy(sizePolicy)
        self.Btn4_Estimate.setCheckable(False)
        self.Btn4_Estimate.setChecked(False)
        self.Btn4_Estimate.setAutoExclusive(False)
        self.Btn4_Estimate.setObjectName("Btn4_Estimate")
        self.verticalLayout.addWidget(self.Btn4_Estimate)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 150, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setLineWidth(5)
        self.frame_2.setObjectName("frame_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1166, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "基本信息"))
        self.label_1.setText(_translate("MainWindow", "姓名："))
        self.label_2.setText(_translate("MainWindow", "性别："))
        self.comboBox.setItemText(0, _translate("MainWindow", "男"))
        self.comboBox.setItemText(1, _translate("MainWindow", "女"))
        self.label_4.setText(_translate("MainWindow", "年龄："))
        self.Btn_New.setText(_translate("MainWindow", "新建"))
        self.Btn_Search.setText(_translate("MainWindow", "查询"))
        self.label_page1.setText(_translate("MainWindow", "1"))
        self.groupBox_BackGround.setTitle(_translate("MainWindow", "生活背景调查研究"))
        self.groupBox_Home.setTitle(_translate("MainWindow", "居住地："))
        self.radioButton_3.setText(_translate("MainWindow", "北京"))
        self.radioButton_4.setText(_translate("MainWindow", "外地"))
        self.groupBox_culture.setTitle(_translate("MainWindow", "文化程度"))
        self.radioButton_16.setText(_translate("MainWindow", "中专及以上"))
        self.radioButton_19.setText(_translate("MainWindow", "初中"))
        self.radioButton_21.setText(_translate("MainWindow", "高中"))
        self.radioButton_23.setText(_translate("MainWindow", "小学"))
        self.groupBox_marriage.setTitle(_translate("MainWindow", "婚姻状况"))
        self.radioButton_39.setText(_translate("MainWindow", "配偶健在"))
        self.radioButton_40.setText(_translate("MainWindow", "丧偶"))
        self.radioButton_41.setText(_translate("MainWindow", "离异"))
        self.groupBox_living.setTitle(_translate("MainWindow", "居住状况"))
        self.radioButton_45.setText(_translate("MainWindow", "独居"))
        self.radioButton_46.setText(_translate("MainWindow", "与子女同住"))
        self.groupBox_smoking.setTitle(_translate("MainWindow", "是否有长期吸烟史"))
        self.radioButton_47.setText(_translate("MainWindow", "是"))
        self.radioButton_66.setText(_translate("MainWindow", "否"))
        self.groupBox_drinking.setTitle(_translate("MainWindow", "是否有长期饮酒史"))
        self.radioButton_67.setText(_translate("MainWindow", "是"))
        self.radioButton_68.setText(_translate("MainWindow", "否"))
        self.groupBox_family.setTitle(_translate("MainWindow", "家族是否有遗传性耳聋史"))
        self.radioButton_69.setText(_translate("MainWindow", "是"))
        self.radioButton_70.setText(_translate("MainWindow", "否"))
        self.groupBox_noise.setTitle(_translate("MainWindow", "是否有长时间噪声接触史"))
        self.radioButton_71.setText(_translate("MainWindow", "是"))
        self.radioButton_72.setText(_translate("MainWindow", "否"))
        self.groupBox_drugs.setTitle(_translate("MainWindow", "是否使用过耳毒性药物（如庆大霉素，链霉素等）"))
        self.radioButton_73.setText(_translate("MainWindow", "是"))
        self.radioButton_74.setText(_translate("MainWindow", "否"))
        self.groupBox_chronic.setTitle(_translate("MainWindow", "是否有以下慢性病（可多选）"))
        self.checkBox_6.setText(_translate("MainWindow", "高血压"))
        self.checkBox_7.setText(_translate("MainWindow", "高血脂"))
        self.checkBox_8.setText(_translate("MainWindow", "糖尿病"))
        self.checkBox_9.setText(_translate("MainWindow", "肿瘤"))
        self.checkBox_10.setText(_translate("MainWindow", "心脑血管疾病"))
        self.label_page2.setText(_translate("MainWindow", "2"))
        self.Btn_Save2.setText(_translate("MainWindow", "保存"))
        self.groupBox_HHIE.setTitle(_translate("MainWindow", "老年人听力障碍调查表（HHIE）"))
        self.groupBox3_1.setTitle(_translate("MainWindow", "1、遇到不熟悉的人时，您会因担心听不清楚而感到窘迫（紧张）吗？"))
        self.radioButton_75.setText(_translate("MainWindow", "会"))
        self.radioButton_76.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_77.setText(_translate("MainWindow", "无"))
        self.groupBox3_2.setTitle(_translate("MainWindow", "2、听力问题使您和家人聊天时会感到有困难(受影响)吗？"))
        self.radioButton_78.setText(_translate("MainWindow", "会"))
        self.radioButton_79.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_80.setText(_translate("MainWindow", "无"))
        self.groupBox3_8.setTitle(_translate("MainWindow", "8、听力问题让您在看电视或者听收音机广播时感到会有困难吗？"))
        self.radioButton_81.setText(_translate("MainWindow", "会"))
        self.radioButton_82.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_83.setText(_translate("MainWindow", "无"))
        self.groupBox3_3.setTitle(_translate("MainWindow", "3、别人跟您小声说话的时候，您觉得听起来很费劲吗？"))
        self.radioButton_84.setText(_translate("MainWindow", "会"))
        self.radioButton_85.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_86.setText(_translate("MainWindow", "无"))
        self.label_3.setText(_translate("MainWindow", "如果您佩戴助听器，请回答在您不用助听器时情况。"))
        self.groupBox3_9.setTitle(_translate("MainWindow", "9、听力问题会让您的私人及社交活动有影响吗？"))
        self.radioButton_87.setText(_translate("MainWindow", "会"))
        self.radioButton_88.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_89.setText(_translate("MainWindow", "无"))
        self.groupBox3_7.setTitle(_translate("MainWindow", "7、会因为听力不好导致您和家人吵架吗?"))
        self.radioButton_90.setText(_translate("MainWindow", "会"))
        self.radioButton_91.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_92.setText(_translate("MainWindow", "无"))
        self.groupBox3_10.setTitle(_translate("MainWindow", "10、在酒店就餐，听力问题会让您与亲友交谈时感到困难吗？"))
        self.radioButton_93.setText(_translate("MainWindow", "会"))
        self.radioButton_94.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_95.setText(_translate("MainWindow", "无"))
        self.groupBox3_6.setTitle(_translate("MainWindow", "6、听力问题会让您经常不愿意参加公众聚会活动吗？"))
        self.radioButton_96.setText(_translate("MainWindow", "会"))
        self.radioButton_97.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_98.setText(_translate("MainWindow", "无"))
        self.groupBox3_5.setTitle(_translate("MainWindow", "5、走亲访友时，您是否因听力不好而感到交往困难？"))
        self.radioButton_99.setText(_translate("MainWindow", "会"))
        self.radioButton_100.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_101.setText(_translate("MainWindow", "无"))
        self.groupBox3_4.setTitle(_translate("MainWindow", "4、听力不好会不会让您感觉自己有缺陷（像残疾人一样）？"))
        self.radioButton_102.setText(_translate("MainWindow", "会"))
        self.radioButton_103.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_104.setText(_translate("MainWindow", "无"))
        self.Btn_Save3.setText(_translate("MainWindow", "保存"))
        self.label_page3.setText(_translate("MainWindow", "3"))
        self.groupBox4_1.setTitle(_translate("MainWindow", "声导抗 "))
        item = self.tableWidget4_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "R"))
        item = self.tableWidget4_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "L"))
        item = self.tableWidget4_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "鼓室图类型"))
        item = self.tableWidget4_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "峰压值"))
        item = self.tableWidget4_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "声顺"))
        item = self.tableWidget4_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "耳道容积"))
        self.groupBox4_3.setTitle(_translate("MainWindow", "PTA"))
        self.tableWidget4_3.setSortingEnabled(False)
        item = self.tableWidget4_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "R"))
        item = self.tableWidget4_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "L"))
        item = self.tableWidget4_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0.25 kHZ"))
        item = self.tableWidget4_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "0.5 kHZ"))
        item = self.tableWidget4_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "1 kHZ"))
        item = self.tableWidget4_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "2 kHZ"))
        item = self.tableWidget4_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "3 kHZ"))
        item = self.tableWidget4_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "4 kHZ"))
        item = self.tableWidget4_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "6 kHZ"))
        item = self.tableWidget4_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8 kHZ"))
        self.groupBox4_2.setTitle(_translate("MainWindow", "DPOAE"))
        item = self.tableWidget4_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "R"))
        item = self.tableWidget4_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "L"))
        item = self.tableWidget4_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0.75 kHZ"))
        item = self.tableWidget4_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1 kHZ"))
        item = self.tableWidget4_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "2 kHZ"))
        item = self.tableWidget4_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4 kHZ"))
        item = self.tableWidget4_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "6 kHZ"))
        item = self.tableWidget4_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "8 kHZ"))
        self.label_page4.setText(_translate("MainWindow", "4"))
        self.Btn_Save4.setText(_translate("MainWindow", "保存"))
        self.softname.setText(_translate("MainWindow", "首都医科大学附属北京潞河医院"))
        self.Btn1_BaseInfo.setText(_translate("MainWindow", "基本信息"))
        self.Btn2_Backgroud.setText(_translate("MainWindow", "背景调查"))
        self.Btn3_HHIES.setText(_translate("MainWindow", "HHIE-S"))
        self.Btn4_Estimate.setText(_translate("MainWindow", "听力评估"))
