# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1169, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(160, 60, 981, 741))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(870, 700, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(40, 120, 611, 281))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(50, 60, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(180, 60, 54, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(230, 60, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(320, 60, 54, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 60, 41, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 170, 131, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 170, 131, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(900, 710, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget.setGeometry(QtCore.QRect(30, 10, 871, 741))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.widget_2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(True)
        self.widget_2.setFont(font)
        self.widget_2.setMouseTracking(True)
        self.widget_2.setObjectName("widget_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 20, 681, 641))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 40, 211, 58))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(10, 27, 57, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(109, 27, 57, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 120, 211, 85))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 0, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout.addWidget(self.radioButton_6, 0, 1, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout.addWidget(self.radioButton_5, 1, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(360, 120, 241, 85))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout_2.addWidget(self.radioButton_9, 1, 1, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout_2.addWidget(self.radioButton_8, 0, 1, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout_2.addWidget(self.radioButton_10, 1, 0, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout_2.addWidget(self.radioButton_7, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 220, 211, 85))
        self.groupBox_6.setObjectName("groupBox_6")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_11.setGeometry(QtCore.QRect(10, 27, 91, 21))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_12.setGeometry(QtCore.QRect(10, 54, 57, 21))
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_13.setGeometry(QtCore.QRect(110, 27, 57, 21))
        self.radioButton_13.setObjectName("radioButton_13")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(360, 40, 241, 58))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_15.setObjectName("radioButton_15")
        self.gridLayout_4.addWidget(self.radioButton_15, 0, 0, 1, 1)
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_17.setObjectName("radioButton_17")
        self.gridLayout_4.addWidget(self.radioButton_17, 0, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 310, 211, 58))
        self.groupBox_8.setObjectName("groupBox_8")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_14.setGeometry(QtCore.QRect(10, 27, 40, 21))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_18 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_18.setGeometry(QtCore.QRect(110, 27, 40, 21))
        self.radioButton_18.setObjectName("radioButton_18")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_9.setGeometry(QtCore.QRect(360, 310, 241, 58))
        self.groupBox_9.setObjectName("groupBox_9")
        self.radioButton_20 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_20.setGeometry(QtCore.QRect(10, 27, 40, 21))
        self.radioButton_20.setObjectName("radioButton_20")
        self.radioButton_22 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_22.setGeometry(QtCore.QRect(120, 27, 40, 21))
        self.radioButton_22.setObjectName("radioButton_22")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 400, 211, 58))
        self.groupBox_10.setObjectName("groupBox_10")
        self.radioButton_24 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_24.setGeometry(QtCore.QRect(10, 27, 40, 21))
        self.radioButton_24.setObjectName("radioButton_24")
        self.radioButton_25 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_25.setGeometry(QtCore.QRect(110, 20, 40, 21))
        self.radioButton_25.setObjectName("radioButton_25")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_11.setGeometry(QtCore.QRect(360, 400, 241, 58))
        self.groupBox_11.setObjectName("groupBox_11")
        self.radioButton_26 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_26.setGeometry(QtCore.QRect(10, 27, 40, 21))
        self.radioButton_26.setObjectName("radioButton_26")
        self.radioButton_27 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_27.setGeometry(QtCore.QRect(120, 27, 40, 21))
        self.radioButton_27.setObjectName("radioButton_27")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_12.setGeometry(QtCore.QRect(20, 480, 581, 58))
        self.groupBox_12.setObjectName("groupBox_12")
        self.radioButton_28 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_28.setGeometry(QtCore.QRect(10, 27, 40, 21))
        self.radioButton_28.setObjectName("radioButton_28")
        self.radioButton_29 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_29.setGeometry(QtCore.QRect(110, 27, 40, 21))
        self.radioButton_29.setObjectName("radioButton_29")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 550, 581, 58))
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout.addWidget(self.checkBox_5)
        self.tabWidget.addTab(self.widget_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(70, 0, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_14.setGeometry(QtCore.QRect(30, 30, 561, 51))
        self.groupBox_14.setObjectName("groupBox_14")
        self.radioButton_30 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_30.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_30.setObjectName("radioButton_30")
        self.radioButton_31 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_31.setGeometry(QtCore.QRect(130, 30, 89, 16))
        self.radioButton_31.setObjectName("radioButton_31")
        self.radioButton_32 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_32.setGeometry(QtCore.QRect(250, 30, 89, 16))
        self.radioButton_32.setObjectName("radioButton_32")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_15.setGeometry(QtCore.QRect(30, 90, 561, 51))
        self.groupBox_15.setObjectName("groupBox_15")
        self.radioButton_33 = QtWidgets.QRadioButton(self.groupBox_15)
        self.radioButton_33.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_33.setObjectName("radioButton_33")
        self.radioButton_34 = QtWidgets.QRadioButton(self.groupBox_15)
        self.radioButton_34.setGeometry(QtCore.QRect(130, 30, 89, 16))
        self.radioButton_34.setObjectName("radioButton_34")
        self.radioButton_35 = QtWidgets.QRadioButton(self.groupBox_15)
        self.radioButton_35.setGeometry(QtCore.QRect(250, 30, 89, 16))
        self.radioButton_35.setObjectName("radioButton_35")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_16.setGeometry(QtCore.QRect(30, 150, 561, 51))
        self.groupBox_16.setObjectName("groupBox_16")
        self.radioButton_36 = QtWidgets.QRadioButton(self.groupBox_16)
        self.radioButton_36.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_36.setObjectName("radioButton_36")
        self.radioButton_37 = QtWidgets.QRadioButton(self.groupBox_16)
        self.radioButton_37.setGeometry(QtCore.QRect(130, 30, 89, 16))
        self.radioButton_37.setObjectName("radioButton_37")
        self.radioButton_38 = QtWidgets.QRadioButton(self.groupBox_16)
        self.radioButton_38.setGeometry(QtCore.QRect(250, 30, 89, 16))
        self.radioButton_38.setObjectName("radioButton_38")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_18.setGeometry(QtCore.QRect(30, 220, 561, 61))
        self.groupBox_18.setObjectName("groupBox_18")
        self.radioButton_42 = QtWidgets.QRadioButton(self.groupBox_18)
        self.radioButton_42.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_42.setObjectName("radioButton_42")
        self.radioButton_43 = QtWidgets.QRadioButton(self.groupBox_18)
        self.radioButton_43.setGeometry(QtCore.QRect(130, 30, 89, 16))
        self.radioButton_43.setObjectName("radioButton_43")
        self.radioButton_44 = QtWidgets.QRadioButton(self.groupBox_18)
        self.radioButton_44.setGeometry(QtCore.QRect(250, 30, 89, 16))
        self.radioButton_44.setObjectName("radioButton_44")
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_20.setGeometry(QtCore.QRect(30, 300, 561, 51))
        self.groupBox_20.setObjectName("groupBox_20")
        self.radioButton_48 = QtWidgets.QRadioButton(self.groupBox_20)
        self.radioButton_48.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_48.setObjectName("radioButton_48")
        self.radioButton_49 = QtWidgets.QRadioButton(self.groupBox_20)
        self.radioButton_49.setGeometry(QtCore.QRect(130, 30, 89, 16))
        self.radioButton_49.setObjectName("radioButton_49")
        self.radioButton_50 = QtWidgets.QRadioButton(self.groupBox_20)
        self.radioButton_50.setGeometry(QtCore.QRect(250, 30, 89, 16))
        self.radioButton_50.setObjectName("radioButton_50")
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_21.setGeometry(QtCore.QRect(30, 370, 561, 51))
        self.groupBox_21.setObjectName("groupBox_21")
        self.radioButton_51 = QtWidgets.QRadioButton(self.groupBox_21)
        self.radioButton_51.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_51.setObjectName("radioButton_51")
        self.radioButton_52 = QtWidgets.QRadioButton(self.groupBox_21)
        self.radioButton_52.setGeometry(QtCore.QRect(130, 30, 89, 16))
        self.radioButton_52.setObjectName("radioButton_52")
        self.radioButton_53 = QtWidgets.QRadioButton(self.groupBox_21)
        self.radioButton_53.setGeometry(QtCore.QRect(250, 30, 89, 16))
        self.radioButton_53.setObjectName("radioButton_53")
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_22.setGeometry(QtCore.QRect(30, 440, 561, 51))
        self.groupBox_22.setObjectName("groupBox_22")
        self.radioButton_54 = QtWidgets.QRadioButton(self.groupBox_22)
        self.radioButton_54.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_54.setObjectName("radioButton_54")
        self.radioButton_55 = QtWidgets.QRadioButton(self.groupBox_22)
        self.radioButton_55.setGeometry(QtCore.QRect(130, 30, 89, 16))
        self.radioButton_55.setObjectName("radioButton_55")
        self.radioButton_56 = QtWidgets.QRadioButton(self.groupBox_22)
        self.radioButton_56.setGeometry(QtCore.QRect(250, 30, 89, 16))
        self.radioButton_56.setObjectName("radioButton_56")
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_23.setGeometry(QtCore.QRect(30, 510, 561, 51))
        self.groupBox_23.setObjectName("groupBox_23")
        self.radioButton_57 = QtWidgets.QRadioButton(self.groupBox_23)
        self.radioButton_57.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_57.setObjectName("radioButton_57")
        self.radioButton_58 = QtWidgets.QRadioButton(self.groupBox_23)
        self.radioButton_58.setGeometry(QtCore.QRect(130, 30, 89, 16))
        self.radioButton_58.setObjectName("radioButton_58")
        self.radioButton_59 = QtWidgets.QRadioButton(self.groupBox_23)
        self.radioButton_59.setGeometry(QtCore.QRect(250, 30, 89, 16))
        self.radioButton_59.setObjectName("radioButton_59")
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_24.setGeometry(QtCore.QRect(30, 580, 561, 51))
        self.groupBox_24.setObjectName("groupBox_24")
        self.radioButton_60 = QtWidgets.QRadioButton(self.groupBox_24)
        self.radioButton_60.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_60.setObjectName("radioButton_60")
        self.radioButton_61 = QtWidgets.QRadioButton(self.groupBox_24)
        self.radioButton_61.setGeometry(QtCore.QRect(130, 30, 89, 16))
        self.radioButton_61.setObjectName("radioButton_61")
        self.radioButton_62 = QtWidgets.QRadioButton(self.groupBox_24)
        self.radioButton_62.setGeometry(QtCore.QRect(250, 30, 89, 16))
        self.radioButton_62.setObjectName("radioButton_62")
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_25.setGeometry(QtCore.QRect(30, 650, 561, 51))
        self.groupBox_25.setObjectName("groupBox_25")
        self.radioButton_63 = QtWidgets.QRadioButton(self.groupBox_25)
        self.radioButton_63.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton_63.setObjectName("radioButton_63")
        self.radioButton_64 = QtWidgets.QRadioButton(self.groupBox_25)
        self.radioButton_64.setGeometry(QtCore.QRect(130, 30, 89, 16))
        self.radioButton_64.setObjectName("radioButton_64")
        self.radioButton_65 = QtWidgets.QRadioButton(self.groupBox_25)
        self.radioButton_65.setGeometry(QtCore.QRect(250, 30, 89, 16))
        self.radioButton_65.setObjectName("radioButton_65")
        self.groupBox_27 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_27.setGeometry(QtCore.QRect(660, 140, 191, 151))
        self.groupBox_27.setObjectName("groupBox_27")
        self.label_6 = QtWidgets.QLabel(self.groupBox_27)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_17.setGeometry(QtCore.QRect(20, 70, 831, 121))
        self.groupBox_17.setObjectName("groupBox_17")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_17)
        self.tableWidget.setGeometry(QtCore.QRect(0, 20, 821, 91))
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_19.setGeometry(QtCore.QRect(20, 250, 831, 141))
        self.groupBox_19.setObjectName("groupBox_19")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.groupBox_19)
        self.tableWidget_5.setGeometry(QtCore.QRect(10, 30, 621, 91))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(6)
        self.tableWidget_5.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        self.groupBox_26 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_26.setGeometry(QtCore.QRect(20, 460, 831, 131))
        self.groupBox_26.setObjectName("groupBox_26")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_26)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 30, 431, 91))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(870, 690, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser.setGeometry(QtCore.QRect(260, 100, 491, 431))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 140, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 140, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.stackedWidget.addWidget(self.page_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 931, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(5)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(220, 10, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 60, 181, 751))
        self.widget.setObjectName("widget")
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 151, 741))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(5)
        self.frame_3.setObjectName("frame_3")
        self.Btn_BaseInfo_2 = QtWidgets.QPushButton(self.frame_3)
        self.Btn_BaseInfo_2.setGeometry(QtCore.QRect(20, 30, 111, 121))
        self.Btn_BaseInfo_2.setAutoDefault(True)
        self.Btn_BaseInfo_2.setObjectName("Btn_BaseInfo_2")
        self.Btn_Estimate_2 = QtWidgets.QPushButton(self.frame_3)
        self.Btn_Estimate_2.setGeometry(QtCore.QRect(20, 360, 111, 121))
        self.Btn_Estimate_2.setObjectName("Btn_Estimate_2")
        self.Btn_Save_2 = QtWidgets.QPushButton(self.frame_3)
        self.Btn_Save_2.setGeometry(QtCore.QRect(20, 530, 111, 121))
        self.Btn_Save_2.setObjectName("Btn_Save_2")
        self.Btn_Estimate_3 = QtWidgets.QPushButton(self.frame_3)
        self.Btn_Estimate_3.setGeometry(QtCore.QRect(20, 190, 111, 121))
        self.Btn_Estimate_3.setObjectName("Btn_Estimate_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1169, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "1"))
        self.groupBox.setTitle(_translate("MainWindow", "基本信息"))
        self.label.setText(_translate("MainWindow", "姓名："))
        self.label_2.setText(_translate("MainWindow", "性别："))
        self.comboBox.setItemText(0, _translate("MainWindow", "男"))
        self.comboBox.setItemText(1, _translate("MainWindow", "女"))
        self.label_5.setText(_translate("MainWindow", "年龄："))
        self.pushButton_4.setText(_translate("MainWindow", "新建"))
        self.pushButton_5.setText(_translate("MainWindow", "查询"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "老年人听力障碍调查表（HHIE）"))
        self.groupBox_3.setTitle(_translate("MainWindow", "居住地："))
        self.radioButton.setText(_translate("MainWindow", "北京"))
        self.radioButton_2.setText(_translate("MainWindow", "外地"))
        self.groupBox_4.setTitle(_translate("MainWindow", "年龄段："))
        self.radioButton_3.setText(_translate("MainWindow", "51-60"))
        self.radioButton_6.setText(_translate("MainWindow", "61-70"))
        self.radioButton_5.setText(_translate("MainWindow", "71-80"))
        self.radioButton_4.setText(_translate("MainWindow", "80以上"))
        self.groupBox_5.setTitle(_translate("MainWindow", "文化程度"))
        self.radioButton_9.setText(_translate("MainWindow", "中专及以上"))
        self.radioButton_8.setText(_translate("MainWindow", "初中"))
        self.radioButton_10.setText(_translate("MainWindow", "高中"))
        self.radioButton_7.setText(_translate("MainWindow", "小学"))
        self.groupBox_6.setTitle(_translate("MainWindow", "婚姻状况"))
        self.radioButton_11.setText(_translate("MainWindow", "配偶健在"))
        self.radioButton_12.setText(_translate("MainWindow", "丧偶"))
        self.radioButton_13.setText(_translate("MainWindow", "离异"))
        self.groupBox_7.setTitle(_translate("MainWindow", "居住状况"))
        self.radioButton_15.setText(_translate("MainWindow", "独居"))
        self.radioButton_17.setText(_translate("MainWindow", "与子女同住"))
        self.groupBox_8.setTitle(_translate("MainWindow", "是否有长期吸烟史"))
        self.radioButton_14.setText(_translate("MainWindow", "是"))
        self.radioButton_18.setText(_translate("MainWindow", "否"))
        self.groupBox_9.setTitle(_translate("MainWindow", "是否有长期饮酒史"))
        self.radioButton_20.setText(_translate("MainWindow", "是"))
        self.radioButton_22.setText(_translate("MainWindow", "否"))
        self.groupBox_10.setTitle(_translate("MainWindow", "家族是否有遗传性耳聋史"))
        self.radioButton_24.setText(_translate("MainWindow", "是"))
        self.radioButton_25.setText(_translate("MainWindow", "否"))
        self.groupBox_11.setTitle(_translate("MainWindow", "是否有长时间噪声接触史"))
        self.radioButton_26.setText(_translate("MainWindow", "是"))
        self.radioButton_27.setText(_translate("MainWindow", "否"))
        self.groupBox_12.setTitle(_translate("MainWindow", "是否使用过耳毒性药物（如庆大霉素，链霉素等）"))
        self.radioButton_28.setText(_translate("MainWindow", "是"))
        self.radioButton_29.setText(_translate("MainWindow", "否"))
        self.groupBox_13.setTitle(_translate("MainWindow", "是否有以下慢性病（可多选）"))
        self.checkBox.setText(_translate("MainWindow", "高血压"))
        self.checkBox_2.setText(_translate("MainWindow", "高血脂"))
        self.checkBox_3.setText(_translate("MainWindow", "糖尿病"))
        self.checkBox_4.setText(_translate("MainWindow", "肿瘤"))
        self.checkBox_5.setText(_translate("MainWindow", "心脑血管疾病"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget_2), _translate("MainWindow", "背景调查"))
        self.label_3.setText(_translate("MainWindow", "如果您佩戴助听器，请回答在您不用助听器时情况。"))
        self.groupBox_14.setTitle(_translate("MainWindow", "1、遇到不熟悉的人时，您会因担心听不清楚而感到窘迫（紧张）吗？"))
        self.radioButton_30.setText(_translate("MainWindow", "会"))
        self.radioButton_31.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_32.setText(_translate("MainWindow", "无"))
        self.groupBox_15.setTitle(_translate("MainWindow", "2、听力问题使您和家人聊天时会感到有困难(受影响)吗？"))
        self.radioButton_33.setText(_translate("MainWindow", "会"))
        self.radioButton_34.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_35.setText(_translate("MainWindow", "无"))
        self.groupBox_16.setTitle(_translate("MainWindow", "3、别人跟您小声说话的时候，您觉得听起来很费劲吗？"))
        self.radioButton_36.setText(_translate("MainWindow", "会"))
        self.radioButton_37.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_38.setText(_translate("MainWindow", "无"))
        self.groupBox_18.setTitle(_translate("MainWindow", "4、听力不好会不会让您感觉自己有缺陷（像残疾人一样）？"))
        self.radioButton_42.setText(_translate("MainWindow", "会"))
        self.radioButton_43.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_44.setText(_translate("MainWindow", "无"))
        self.groupBox_20.setTitle(_translate("MainWindow", "5、走亲访友时，您是否因听力不好而感到交往困难？"))
        self.radioButton_48.setText(_translate("MainWindow", "会"))
        self.radioButton_49.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_50.setText(_translate("MainWindow", "无"))
        self.groupBox_21.setTitle(_translate("MainWindow", "6、听力问题会让您经常不愿意参加公众聚会活动吗？"))
        self.radioButton_51.setText(_translate("MainWindow", "会"))
        self.radioButton_52.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_53.setText(_translate("MainWindow", "无"))
        self.groupBox_22.setTitle(_translate("MainWindow", "7、会因为听力不好导致您和家人吵架吗?"))
        self.radioButton_54.setText(_translate("MainWindow", "会"))
        self.radioButton_55.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_56.setText(_translate("MainWindow", "无"))
        self.groupBox_23.setTitle(_translate("MainWindow", "8、听力问题让您在看电视或者听收音机广播时感到会有困难吗？"))
        self.radioButton_57.setText(_translate("MainWindow", "会"))
        self.radioButton_58.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_59.setText(_translate("MainWindow", "无"))
        self.groupBox_24.setTitle(_translate("MainWindow", "9、听力问题会让您的私人及社交活动有影响吗？"))
        self.radioButton_60.setText(_translate("MainWindow", "会"))
        self.radioButton_61.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_62.setText(_translate("MainWindow", "无"))
        self.groupBox_25.setTitle(_translate("MainWindow", "10、在酒店就餐，听力问题会让您与亲友交谈时感到困难吗？"))
        self.radioButton_63.setText(_translate("MainWindow", "会"))
        self.radioButton_64.setText(_translate("MainWindow", "有时有点"))
        self.radioButton_65.setText(_translate("MainWindow", "无"))
        self.groupBox_27.setTitle(_translate("MainWindow", "测评结果："))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "HHIE-S"))
        self.groupBox_17.setTitle(_translate("MainWindow", "PTA"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "R"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "L"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0.25 kHZ"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "0.5 kHZ"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "1 kHZ"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "2 kHZ"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "3 kHZ"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "4 kHZ"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "6 kHZ"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8 kHZ"))
        self.groupBox_19.setTitle(_translate("MainWindow", "DPOAE"))
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "R"))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "L"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "0.75 kHZ"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "1 kHZ"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "2 kHZ"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4 kHZ"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "6 kHZ"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "8 kHZ"))
        self.groupBox_26.setTitle(_translate("MainWindow", "声导抗 "))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "R"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "L"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "鼓室图类型"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "峰压值"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "声顺"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "耳道容积"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "听力评估"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.label_4.setText(_translate("MainWindow", "首都医科大学附属北京潞河医院"))
        self.Btn_BaseInfo_2.setText(_translate("MainWindow", "基本信息"))
        self.Btn_Estimate_2.setText(_translate("MainWindow", "听力评估"))
        self.Btn_Save_2.setText(_translate("MainWindow", "存储查询"))
        self.Btn_Estimate_3.setText(_translate("MainWindow", "HHIE-S"))
